import { type ClassValue, clsx } from "clsx"
import { twMerge } from "tailwind-merge"
import { supabase } from './supabase'
import type { MCQQuestion } from '../types'

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs))
}

/**
 * Calls the `generate-mcqs` edge function to get 10 "get to know you" MCQs
 * generated by GPT based on all players' self-answers in the current event.
 *
 * @param requestingPlayerId - The current player's ID (used for auth context)
 * @returns An object with the event_id and the generated MCQ questions
 */
export async function generateMCQs(
  requestingPlayerId: string,
): Promise<{ event_id: string; questions: MCQQuestion[] }> {
  const { data, error } = await supabase.functions.invoke<{
    event_id: string
    questions: MCQQuestion[]
  }>('generate-mcqs', {
    body: { requesting_player_id: requestingPlayerId },
  })

  if (error) throw new Error(error.message)
  if (!data) throw new Error('No data returned from generate-mcqs')

  return data
}
